
name: Update Countries JSON

# Quand exécuter l'action
on:
  schedule:
    - cron: '0 0 1 1 *' # Tous les 6 mois
  workflow_dispatch: # permet de lancer manuellement l'action

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python (ou Node si tu préfères)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Download latest GeoJSON
        run: |
          python scripts/update_countries.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add countries.json
          git commit -m "Update countries.json [ci skip]" || echo "No changes to commit"
          git push
